"""Report exporter engine supporting JSON, Markdown, and HTML formats with token redaction."""

import json
import re
from typing import Any, Dict
from jinja2 import Template

from forgelens.audit.engine import AuditResult


def redact_sensitive_keys(data: Any) -> Any:
    """Recursively redacts API keys and tokens from report data structures."""
    if isinstance(data, str):
        # Redact patterns resembling API keys (e.g. sk-..., hf_...)
        redacted = re.sub(r"sk-[a-zA-Z0-9_-]{20,}", "sk-***REDACTED***", data)
        redacted = re.sub(r"hf_[a-zA-Z0-9_-]{20,}", "hf_***REDACTED***", redacted)
        return redacted
    elif isinstance(data, dict):
        new_dict = {}
        for k, v in data.items():
            if any(term in k.lower() for term in ["key", "token", "secret", "auth", "password"]):
                new_dict[k] = "***REDACTED***"
            else:
                new_dict[k] = redact_sensitive_keys(v)
        return new_dict
    elif isinstance(data, list):
        return [redact_sensitive_keys(item) for item in data]
    return data


MARKDOWN_TEMPLATE = """# ForgeLens Audit Report: {{ audit.repo_id }}

- **Audit Type:** {{ audit.audit_type | upper }}
- **Revision / SHA:** {{ audit.revision }}
- **Profile:** {{ audit.profile_name }}
- **AI Provider Enabled:** {{ audit.ai_enabled }} {% if audit.ai_enabled %}({{ audit.ai_provider_name }} / {{ audit.ai_model_name }}){% endif %}
- **Final Status:** **{{ audit.scores.final_status }}**
- **Weighted Overall Score:** **{{ audit.scores.weighted_total_score }} / 100**

---

## Category Scores

| Category | Score |
|---|---|
{% for cat, score in audit.scores.category_scores.items() %}
| {{ cat | capitalize }} | {{ score }} / 100 |
{% endfor %}

---

## Status Assessment & Reasons
{% for reason in audit.scores.status_reasons %}
- {{ reason }}
{% endfor %}

---

## Measured Evidence
{% for item in audit.evidence['items'] %}
### {{ item.claim }}
- **Measurement:** `{{ item.measurement }}`
{% if item.ai_interpretation %}
- **Interpretation:** {{ item.ai_interpretation }}
{% endif %}
{% endfor %}

---

{% if audit.warnings %}
## Warnings
{% for w in audit.warnings %}
- ⚠️ {{ w }}
{% endfor %}
{% endif %}

*Generated by ForgeLens — AI Dataset & Model Auditor (Remote Audit First).*
"""


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ForgeLens Report - {{ audit.repo_id }}</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; margin: 40px; color: #222; background: #f9f9fb; }
        .card { background: #fff; padding: 24px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.06); margin-bottom: 24px; }
        h1 { margin-top: 0; color: #111; }
        .badge { display: inline-block; padding: 6px 12px; border-radius: 4px; font-weight: bold; color: #fff; }
        .SUITABLE { background-color: #10b981; }
        .REVIEW_REQUIRED { background-color: #f59e0b; }
        .NOT_SUITABLE { background-color: #ef4444; }
        .INSUFFICIENT_DATA { background-color: #6b7280; }
        table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        th, td { text-align: left; padding: 10px; border-bottom: 1px solid #eee; }
        th { background: #f3f4f6; }
        pre { background: #2d3748; color: #edf2f7; padding: 12px; border-radius: 6px; overflow-x: auto; }
    </style>
</head>
<body>
    <div class="card">
        <h1>ForgeLens Audit Report: {{ audit.repo_id }}</h1>
        <p>
            <strong>Status:</strong> <span class="badge {{ audit.scores.final_status }}">{{ audit.scores.final_status }}</span>
            &nbsp; | &nbsp;
            <strong>Overall Score:</strong> {{ audit.scores.weighted_total_score }} / 100
        </p>
        <p><strong>Audit Type:</strong> {{ audit.audit_type | upper }} | <strong>Profile:</strong> {{ audit.profile_name }} | <strong>Revision:</strong> {{ audit.revision }}</p>
    </div>

    <div class="card">
        <h2>Category Scores</h2>
        <table>
            <thead>
                <tr><th>Category</th><th>Score</th></tr>
            </thead>
            <tbody>
                {% for cat, score in audit.scores.category_scores.items() %}
                <tr><td>{{ cat | capitalize }}</td><td><strong>{{ score }}</strong> / 100</td></tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="card">
        <h2>Evidence & Findings</h2>
        {% for item in audit.evidence['items'] %}
            <h3>{{ item.claim }}</h3>
            <pre>{{ item.measurement | tojson(indent=2) }}</pre>
            {% if item.ai_interpretation %}
                <p><em>{{ item.ai_interpretation }}</em></p>
            {% endif %}
        {% endfor %}
    </div>
</body>
</html>
"""


class ReportExporter:
    """Exports AuditResult objects into JSON, Markdown, and HTML reports."""

    @staticmethod
    def export_json(audit_result: AuditResult) -> str:
        data = audit_result.model_dump()
        sanitized = redact_sensitive_keys(data)
        return json.dumps(sanitized, ensure_ascii=False, indent=2)

    @staticmethod
    def export_markdown(audit_result: AuditResult) -> str:
        sanitized_dict = redact_sensitive_keys(audit_result.model_dump())
        template = Template(MARKDOWN_TEMPLATE)
        return template.render(audit=sanitized_dict)

    @staticmethod
    def export_html(audit_result: AuditResult) -> str:
        sanitized_dict = redact_sensitive_keys(audit_result.model_dump())
        template = Template(HTML_TEMPLATE)
        return template.render(audit=sanitized_dict)
